import test from 'node:test';import assert from 'node:assert/strict';
import {Simulation} from '../backend/simulation.mjs';import world from '../backend/world.json' with {type:'json'};
function room(){const s=new Simulation();s.join('bruno');s.join('nala');return s;}
test('inputs move both roles; coordinates, HP and rewards supplied by clients are ignored',()=>{const s=room();const a=s.data.players.bruno,b=s.data.players.nala,x=a.x,bx=b.x;s.command('bruno',{type:'state',x:0,y:0,hp:999,gold:999});assert.equal(a.x,x);assert.equal(a.gold,45);s.command('bruno',{type:'input',x:-1,y:0},1000);s.command('nala',{type:'input',x:1,y:0},1000);s.tick(.1,1050);assert(a.x<x);assert(b.x>bx);assert(Number.isFinite(a.x));s.command('bruno',{type:'input',x:Infinity,y:0},1100);s.tick(.1,1100);assert(Number.isFinite(a.x));});
test('attack and skill cooldowns, MP, stamina, damage and defeat rewards have one authority',()=>{const s=room(),p=s.data.players.bruno,e=s.data.enemies[0];p.x=e.x-35;p.y=e.y;p.dirX=1;p.dirY=0;const hp=e.hp;s.command('bruno',{type:'attack'},1000);const after=e.hp;assert(after<hp);s.command('bruno',{type:'attack'},1001);assert.equal(e.hp,after);const mp=p.mp;s.command('bruno',{type:'skill'},1002);assert(p.mp<mp);const mp2=p.mp;s.command('bruno',{type:'skill'},1003);assert.equal(p.mp,mp2);const stam=p.stam;s.command('bruno',{type:'dash'},1004);assert(p.stam<stam);e.hp=1;e.alive=true;p.x=e.x-35;p.y=e.y;p.attackCd=0;s.command('bruno',{type:'attack'},2000);const xp=p.xp,kills=s.data.kills,drops=s.data.drops.length;s.command('bruno',{type:'attack'},2001);assert.equal(s.data.kills,kills);assert.equal(p.xp,xp);assert.equal(s.data.drops.length,drops);});
test('simultaneous pickup and chest attempts cannot duplicate loot',()=>{const s=room(),a=s.data.players.bruno,b=s.data.players.nala;Object.assign(b,{x:a.x,y:a.y});s.data.drops=[{id:'only',kind:'coins',amount:12,scene:'world',x:a.x,y:a.y}];s.tick(.1,1000);assert.equal(a.gold+b.gold,102);assert.equal(s.data.drops.length,0);const c=s.data.chests[0];for(const p of [a,b])Object.assign(p,{scene:c.scene,x:c.x,y:c.y});s.command('bruno',{type:'interact'});s.command('nala',{type:'interact'});assert(c.open);assert.equal(a.inventory.length+b.inventory.length,1);assert(Object.values(a.equip).some(Boolean));});
test('boss, victory, final chest gate and postgame are shared; king never respawns',()=>{const s=room(),p=s.data.players.bruno,c=s.data.chests.find(c=>c.final),king=s.data.enemies.find(e=>e.type==='king');Object.assign(p,{scene:'dungeon',x:c.x,y:c.y});s.command('bruno',{type:'interact'});assert(!c.open);s.damage(p,king,100000,1000);assert(s.data.victory);s.command('bruno',{type:'interact'});assert(c.open);s.tick(.1,100000);assert(!king.alive);const snap=s.snapshot();assert.equal(snap.victory,true);assert(snap.events.some(e=>e.kind==='victory'));s.command('bruno',{type:'input',x:1,y:0},100001);const x=p.x;s.tick(.1,100010);assert(p.x>x);});
test('quests share flags and each player can claim rewards exactly once at the correct NPC',()=>{const s=room(),a=s.data.players.bruno,b=s.data.players.nala,n=world.npcs.find(n=>n.name==='Toto');for(const p of [a,b])Object.assign(p,{x:n.x,y:n.y+60});s.command('bruno',{type:'quest',id:'cats'});s.data.kills=6;s.quests();for(const r of ['bruno','nala']){s.command(r,{type:'quest',id:'cats'});const gold=s.data.players[r].gold;s.command(r,{type:'quest',id:'cats'});assert.equal(s.data.players[r].gold,gold);assert.equal(gold,125);}assert(s.data.quests.cats.claimed);});
test('gear and skill upgrades affect only their owner and cannot heal dead players',()=>{const s=room(),a=s.data.players.bruno,b=s.data.players.nala;const atk=b.attack;s.item(a,{slot:'weapon',power:40,name:'test'});assert(a.attack>40);assert.equal(b.attack,atk);s.command('nala',{type:'equip',id:a.inventory[0].id});assert.equal(b.attack,atk);s.command('bruno',{type:'upgrade',skill:'power'});assert.equal(a.points,0);s.command('bruno',{type:'upgrade',skill:'power'});assert.equal(a.skills.power,1);a.hp=0;s.refresh(a);assert.equal(a.hp,0);});
test('dead players respawn without sending input, keeping inventory and progress',()=>{const s=room(),p=s.data.players.bruno;s.item(p,{slot:'armor',power:10,name:'test'});const inventory=structuredClone(p.inventory);p.hp=1;p.inv=0;s.hurt(p,100000,1000);assert.equal(p.hp,0);s.tick(.1,4000);assert.equal(p.hp,p.maxHp);assert.equal(p.scene,'world');assert.deepEqual(p.inventory,inventory);});
test('scene transitions are checked server-side; room state survives reload',()=>{const s=room(),p=s.data.players.bruno;Object.assign(p,{x:world.cave.x,y:world.cave.y+90});s.command('bruno',{type:'interact'});assert.equal(p.scene,'dungeon');s.command('bruno',{type:'interact'});assert.equal(p.scene,'world');const restored=new Simulation(structuredClone(s.data));restored.join('bruno');assert.deepEqual(restored.data,s.data);});
test('idle enemies still attack; town is safe; stale inputs stop movement',()=>{const s=room(),p=s.data.players.bruno,e=s.data.enemies[0];Object.assign(p,{x:e.x+20,y:e.y,inv:0});e.cd=0;const hp=p.hp;s.tick(.1,1000);assert(p.hp<hp);Object.assign(p,{x:world.spawn.x,y:world.spawn.y});Object.assign(e,{x:p.x+20,y:p.y,cd:0});p.inv=0;const safeHp=p.hp;s.tick(.1,2000);assert.equal(p.hp,safeHp);s.command('bruno',{type:'input',x:1,y:0},2000);const x=p.x;s.tick(.1,2400);assert.equal(p.x,x);});
test('material drops are exclusive and equipment references survive persistence',()=>{const s=room(),a=s.data.players.bruno,b=s.data.players.nala;Object.assign(b,{x:a.x,y:a.y});s.data.drops=[{id:'metal-once',kind:'metal',amount:1,x:a.x,y:a.y,scene:'world'},{id:'herb-once',kind:'herb',amount:1,x:a.x,y:a.y,scene:'world'}];s.tick(.1,1000);s.tick(.1,1100);assert.equal(a.metal+b.metal,1);assert.equal(a.herb+b.herb,1);s.item(a,{slot:'weapon',power:10,name:'test'});const restored=new Simulation(JSON.parse(JSON.stringify(s.data)));const p=restored.data.players.bruno;assert.equal(p.equip.weapon,p.inventory[0]);});
