// Export the exact collision geometry and spawn definitions from the stable client.
const fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('public/index.html','utf8');
function fn(name){const start=html.indexOf('function '+name+'(');if(start<0)throw Error(name);const lineEnd=html.indexOf('\n',start);if(html.slice(start,lineEnd).trimEnd().endsWith('}'))return html.slice(start,lineEnd);return html.slice(start,html.indexOf('\n}',start)+2)}
const map=JSON.parse(html.match(/const EMBEDDED_VILLAGE_MAP = (.*);/)[1]);
const names=['buildVillageProps','computeVillageVisuals','isNearFountainVisual','rebuildWorldCollisions','isInsideTownSafeZone','resolveVillageSpawn','projectEnemySpawnOutsideTown','applyWorldHotfixes','loadTiledMap','circleRectHit','npcPositionBlocked','makeEnemy','seedDynamicWorld'];
const s={console,result:null};vm.createContext(s);
vm.runInContext(`const TILE_SIZE=48;const propMap=o=>Object.fromEntries((o.properties||[]).map(p=>[p.name,p.value]));const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const rnd=(a,b)=>(a+b)/2;function initWorldNpcStates(){};function restAtInn(){};let mapModel,mapWidthPx,mapHeightPx,tileLayers,mapObjects=[],mapDecor=[],mapCollisions=[],spawnPoint,villageGroundBounds,villageCobbleAnchors,villagePlaza,villageCenterpiece,villageProps,caveTrigger,enemies,chests,loot,effects,hazards,respawnQueue,gameCompleted,victoryShown,victoryDelay,interiorNpcs;${names.map(fn).join('\n')};loadTiledMap(${JSON.stringify(map)});seedDynamicWorld();result={width:mapWidthPx,height:mapHeightPx,spawn:spawnPoint,safe:villageGroundBounds,collisions:mapCollisions,enemies,chests,npcs:mapObjects.filter(o=>o.type==='npc'),buildings:mapObjects.filter(o=>o.type==='building'),cave:mapObjects.find(o=>o.type==='cave')};`,s);
fs.writeFileSync('backend/world.json',JSON.stringify(s.result));console.log({spawn:s.result.spawn,enemies:s.result.enemies.length,collisions:s.result.collisions.length,npcs:s.result.npcs.map(n=>({name:n.name,x:n.x,y:n.y}))});
